# Generated by Django 4.1.2 on 2022-10-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.TextField(default='fred'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='name',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
