# Generated by Django 4.1.2 on 2022-11-25 14:29

from django.db import migrations, models
import things.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_alter_thing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='role',
            field=models.CharField(choices=[('greg', things.models.Bob['Greg']), ('james', things.models.Bob['James'])], default='greg', max_length=10),
        ),
    ]
