# Generated by Django 4.1.2 on 2022-11-25 14:31

from django.db import migrations, models
import things.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_thing_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='role',
            field=models.CharField(choices=[(things.models.Bob['Greg'], 'greg'), (things.models.Bob['James'], 'james')], default=things.models.Bob['Greg'], max_length=10),
        ),
    ]
