# Generated by Django 4.1.2 on 2022-11-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_alter_thing_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='role',
            field=models.CharField(choices=[('greg', 'greg'), ('james', 'greg')], default='greg', max_length=10),
        ),
    ]
